name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch: # Para permitir la ejecución manual

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}/flask-app:latest

      - name: Deploy to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VPS_IP: ${{ secrets.VPS_IP }}
          VPS_USER: ${{ secrets.VPS_USER }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "${SSH_PRIVATE_KEY}" > key.pem
          chmod 600 key.pem
          scp -o StrictHostKeyChecking=no -i key.pem docker-compose.yml $VPS_USER@$VPS_IP:/home/$VPS_USER/
          ssh -o StrictHostKeyChecking=no -i key.pem $VPS_USER@$VPS_IP 'bash -s' << 'EOF'
            cd /home/$VPS_USER/
            echo $GITHUB_TOKEN | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
            docker-compose down
            docker-compose pull
            docker-compose up -d
          EOF
